In [2]:
from KNN import KNN

In [3]:
??KNN

Init signature: KNN()
Docstring:      <no docstring>
Source:
class KNN():
    def knn(data, query, k, dist_fn, choice_fn):
        neighbor_dist_and_indices = []
        for i, example in enumerate(data):
            distance = dist_fn(example[:-1], query)
            neighbor_dist_and_indices.append((distance, i))

        print('dist&indices : ',neighbor_dist_and_indices)
        sorted_neighbor_dist_and_indices = sorted(neighbor_dist_and_indices)

        k_nearest_neighbor_dist_and_indices = sorted_neighbor_dist_and_indices[:k]
        print('sorted k = 3 : ', k_nearest_neighbor_dist_and_indices)
        k_entries_labels = [data[i][1] for distance, i in k_nearest_neighbor_dist_and_indices]
        print('k_entries_labels',k_entries_labels)

        return k_nearest_neighbor_dist_and_indices, choice_fn(k_entries_labels)


    # mean is selected as choice_fn , if regression
    def mean(labels):
        return sum(labels)/len(labels)


    # mode is selected as choice_fn , if classification
    def mode(labels):
        return Counter(labels).most_common(1)[0][0]


    def euclidean_dist(p1, p2):
        sum_sq_dist = 0
        for i in range(len(p1)):
            sum_sq_dist += math.pow(p1[i] - p2[i], 2)
        return math.sqrt(sum_sq_dist)
File:           ~/Desktop/KNN/Basic-Machine-Learning-Projects/KNN/KNN.py
Type:           type
Subclasses:

In [4]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [5]:
dataset = pd.read_csv('selfmovie_dataset.csv')

In [6]:
dataset.tail(5)

,Movie_ID,Movie_Name,IMDB_Rating,Biography,Drama,Thriller,Comedy,Crime,Mystery,History,Label
25,17,Thor: Ragnarok,7.9,0,0,0,1,0,0,0,0
26,12,Spirit: Stallion of the Cimarron,7.1,0,0,0,0,0,0,0,0
27,1,Hacksaw Ridge,8.2,1,1,0,0,0,0,1,0
28,86,12 Years a Slave,8.1,1,1,0,0,0,0,1,0
29,46,Queen of Katwe,7.4,1,1,0,0,0,0,0,0

In [13]:
# df2 = (df['genre'].str.get_dummies(', ').rename(columns=lambda x: x.strip('"')))

In [14]:
# df2

,Action,Adult,Adventure,Animation,Biography,Comedy,Crime,Documentary,Drama,Family,...,Musical,Mystery,News,Reality-TV,Romance,Sci-Fi,Sport,Thriller,War,Western
0,0,0,0,0,1,0,1,0,1,0,...,0,0,0,0,0,0,0,0,0,0
1,0,0,0,0,0,0,0,0,1,0,...,0,0,0,0,0,0,0,0,0,0
2,0,0,0,0,0,0,0,0,1,0,...,0,0,0,0,0,0,0,0,0,0
3,0,0,1,0,0,0,0,0,1,0,...,0,0,0,0,0,0,0,0,0,0
4,0,0,0,0,1,0,0,0,1,0,...,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
81268,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,1,0,0
81269,0,0,0,0,0,0,0,0,1,0,...,0,0,0,0,0,0,0,0,0,0
81270,0,0,0,0,0,0,0,0,1,0,...,0,0,0,0,0,0,0,0,0,0
81271,0,0,0,0,0,0,0,0,1,0,...,0,0,0,0,0,0,0,0,0,0
81272,0,0,0,0,0,0,0,0,1,1,...,0,0,0,0,0,0,0,0,0,0

In [8]:
dataset.isnull().values.any()

False

In [17]:
def recommend_movies(movie_query, k_recommendations):
    raw_movie_data = []
    with open('selfmovie_dataset.csv','r') as md:
        next(md) #discard the first line
        
        for line in md.readlines():
            data_row = line.strip().split(',')
            raw_movie_data.append(data_row)
    print('raw_movie_data : ',raw_movie_data[:5])
    
    movies_rec_data = []
    for row in raw_movie_data:
        data_row = list(map(float, row[2:]))
        movies_rec_data.append(data_row)
        
    print('movies_rec_data : ',movies_rec_data[:5])
    
    rec_indices, _ = KNN.knn(movies_rec_data, movie_query, k = k_recommendations, dist_fn = KNN.euclidean_dist, choice_fn = lambda x: None)
    print('rec_indices : ',rec_indices)
    movie_recommendations = []
    for _, index in rec_indices:
        movie_recommendations.append(raw_movie_data[index])
    return movie_recommendations

In [18]:
hacksaw = dataset.iloc[27,2:].values
hacksaw

array([8.2, 1, 1, 0, 0, 0, 0, 1, 0], dtype=object)

In [19]:
recommended_movies = recommend_movies(hacksaw, 5)

raw_movie_data :  [['58', 'The Imitation Game', '8', '1', '1', '1', '0', '0', '0', '0', '0'], ['8', 'Ex Machina', '7.7', '0', '1', '0', '0', '0', '1', '0', '0'], ['46', 'A Beautiful Mind', '8.2', '1', '1', '0', '0', '0', '0', '0', '0'], ['62', 'Good Will Hunting', '8.3', '0', '1', '0', '0', '0', '0', '0', '0'], ['97', 'Forrest Gump', '8.8', '0', '1', '0', '0', '0', '0', '0', '0']]
movies_rec_data :  [[8.0, 1.0, 1.0, 1.0, 0.0, 0.0, 0.0, 0.0, 0.0], [7.7, 0.0, 1.0, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0], [8.2, 1.0, 1.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0], [8.3, 0.0, 1.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0], [8.8, 0.0, 1.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0]]
dist&indices :  [(1.42828568570857, 0), (1.8027756377319943, 1), (1.0, 2), (1.4177446878757827, 3), (1.5362291495737221, 4), (1.9899748742132395, 5), (1.5362291495737215, 6), (2.879236009777593, 7), (1.7578395831246945, 8), (1.7320508075688767, 9), (1.7320508075688767, 10), (2.1540659228538015, 11), (1.469693845669907, 12), (2.0, 13), (1.9078784028338909, 14), (1.8330302779823364, 15), (1.0770329614269007, 16), (1.7776388834631178, 17), (1.6763054614240207, 18), (1.9519221295943132, 19), (2.7495454169735036, 20), (1.6763054614240207, 21), (1.7435595774162693, 22), (2.449489742783178, 23), (1.7349351572897471, 24), (2.0223748416156684, 25), (2.051828452868319, 26), (0.0, 27), (0.09999999999999964, 28), (1.2806248474865691, 29)]
sorted k = 3 :  [(0.0, 27), (0.09999999999999964, 28), (1.0, 2), (1.0770329614269007, 16), (1.2806248474865691, 29)]
k_entries_labels [1.0, 1.0, 1.0, 1.0, 1.0]
rec_indices :  [(0.0, 27), (0.09999999999999964, 28), (1.0, 2), (1.0770329614269007, 16), (1.2806248474865691, 29)]

In [20]:
recommended_movies

[['1', 'Hacksaw Ridge', '8.2', '1', '1', '0', '0', '0', '0', '1', '0'],
 ['86', '12 Years a Slave', '8.1', '1', '1', '0', '0', '0', '0', '1', '0'],
 ['46', 'A Beautiful Mind', '8.2', '1', '1', '0', '0', '0', '0', '0', '0'],
 ['44', 'The Wind Rises', '7.8', '1', '1', '0', '0', '0', '0', '0', '0'],
 ['46', 'Queen of Katwe', '7.4', '1', '1', '0', '0', '0', '0', '0', '0']]